### PR TITLE
Error and response refactorisation from form service

### PR DESCRIPTION
**Pull request by TeddyAndersson**
The data access layer is now refactored to have less repetative code. This mainly effects creation of success and error responses.

### CODE REVIEW

**Review by sammed — APPROVED** [review]

**Comment by zilaei** [comment]
Class ResourceNotFoundError duplicated (error.js).

**Comment by zilaei** [comment]
error.js: DomainError constructor: Error (super) dose not expect argument msg.
eample.dal.js: 
Using console.log instead of logger.
Missing await for async calls.

**Comment by TeddyAndersson** [comment]
Vad gjorde du för att få det felmeddelandet @zilaei ?

**Comment by TeddyAndersson** [comment]
Never mind hittade det, måste ha varit något som hänt när jag löste conflicts igår

**Pull request merged**
